(() => {
  const STORE='dextairBookingsV2';
  const LEGACY_STORE='dextairBookingsV1';
  const frame=document.getElementById('app');

  const readStore=name=>{try{return JSON.parse(localStorage.getItem(name)||'{}')||{};}catch{return {};}};
  const db=()=>{const modern=readStore(STORE), legacy=readStore(LEGACY_STORE);return {...legacy,...modern};};
  const save=r=>{const x=readStore(STORE);x[r.ref.toUpperCase()]=r;localStorage.setItem(STORE,JSON.stringify(x));};
  const lookup=(ref,last)=>{const r=db()[String(ref||'').trim().toUpperCase()];return r&&String(r.last).toLowerCase()===String(last||'').trim().toLowerCase()?r:null;};
  const key=s=>`${s.date}-DX${s.flightNo}-${s.from}-${s.to}`;
  const seat=(r,s,p=0)=>r.seats?.[key(s)]?.[p]||r.seats?.[key(s)]?.[String(p)]||'—';
  const intlCodes=new Set(['NAS','CUN','MBJ','PUJ','YYZ','YUL','SXM','HAV','FPO','YVR','SDQ']);
  const isInternational=s=>intlCodes.has(s.from)||intlCodes.has(s.to);
  const paxName=(r,p)=>p===0?`${r.first} ${r.last}`:`Traveler ${p+1} ${r.last}`;
  const fmtDate=s=>new Date(s.date+'T12:00:00').toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'});
  const pad=n=>String(n).padStart(2,'0');
  const timeFromMinutes=m=>`${pad(Math.floor((((m%1440)+1440)%1440)/60))}:${pad((((m%1440)+1440)%1440)%60)}`;
  const addMinutes=(m,delta)=>timeFromMinutes((Number(m)||0)+delta);
  const checkinRecord=(r,s)=>r.checkin?.[key(s)]||null;

  function install(d,w){
    const q=id=>d.getElementById(id);
    const run=code=>{try{return w.eval(code);}catch{return undefined;}};
    const fmt=t=>run(`hhmm(${Number(t)||0})`)||timeFromMinutes(Number(t)||0);
    if(!q('findTripBtn')||q('dextairBookingFeatureV2'))return;

    const marker=d.createElement('span');marker.id='dextairBookingFeatureV2';marker.hidden=true;d.body.appendChild(marker);
    const style=d.createElement('style');
    style.textContent=`
      .booking-tool-output{margin-top:14px}.booking-card{border:1px solid #e1e4e8;border-radius:18px;padding:18px;background:#fff;box-shadow:0 8px 24px #1111;max-width:100%}
      .booking-card h3{margin:0 0 8px}.booking-meta{color:#6f7681;font-size:13px;line-height:1.55}.booking-segment{background:#f5f6f8;border-radius:14px;padding:14px;margin-top:10px}
      .booking-segment-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.checkin-state{display:inline-flex;margin-top:8px;border-radius:999px;padding:7px 10px;background:#eef8f1;color:#276749;font-size:12px;font-weight:900}.checkin-state.done{background:#e7f5ec;color:#21633a}
      .dx-action{border:0;border-radius:10px;padding:11px 14px;background:#111318;color:#fff;font-weight:900;cursor:pointer}.dx-action.red{background:#b5121b}.dx-action.secondary{background:#eef0f2;color:#222}.dx-action:disabled{opacity:.45;cursor:not-allowed}
      .checkin-shell{margin-top:14px;border:1px solid #dfe3e8;border-radius:18px;overflow:hidden;background:#fff}.checkin-progress{display:grid;grid-template-columns:repeat(4,1fr);background:#f5f6f8;border-bottom:1px solid #e4e7eb}.checkin-step-tab{padding:12px 8px;text-align:center;font-size:11px;font-weight:900;color:#7a818b}.checkin-step-tab.active{background:#fff;color:#b5121b;box-shadow:inset 0 -3px 0 #b5121b}.checkin-step-tab.done{color:#276749}.checkin-pane{padding:18px}.checkin-pane h3{margin:0 0 8px}
      .checkin-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.checkin-grid label,.checkin-choice{font-size:12px;font-weight:800;color:#555}.checkin-grid input,.checkin-grid select{width:100%;min-height:44px;margin-top:6px;border:1px solid #d5d9df;border-radius:10px;padding:10px;background:#fff}
      .checkin-choice{display:flex;gap:10px;align-items:flex-start;border:1px solid #e1e4e8;border-radius:12px;padding:12px;margin-top:10px;color:#333}.checkin-choice input{width:auto;min-height:0;margin:2px 0 0}.pax-check-card{border:1px solid #e1e4e8;border-radius:13px;padding:13px;margin-top:10px}.pax-check-card strong{display:block}.pax-check-card small{display:block;color:#737984;margin-top:4px}.ops-box{background:#f5f6f8;border-radius:13px;padding:13px;margin-top:12px;color:#4f5660;font-size:13px;line-height:1.55}.ops-box b{color:#17191f}.checkin-nav{display:flex;justify-content:space-between;gap:10px;margin-top:18px}
      .boarding-pass{margin-top:14px;border:1px solid #d6dbe1;border-radius:18px;overflow:hidden;background:#fff}.boarding-pass-head{display:flex;justify-content:space-between;gap:12px;background:#111318;color:#fff;padding:14px 16px}.boarding-pass-route{display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:center;padding:18px 16px;border-bottom:1px dashed #ccd1d8}.boarding-pass-route strong{font-size:28px}.boarding-pass-route .arrow{text-align:center;color:#8a919c}.boarding-pass-body{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:16px}.boarding-pass-body small{display:block;color:#747b86;margin-bottom:4px}.boarding-pass-foot{border-top:1px dashed #ccd1d8;padding:11px 16px;font-size:12px;color:#6f7681;display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}
      @media(max-width:600px){.booking-segment-head{flex-direction:column}.checkin-progress{grid-template-columns:1fr 1fr}.checkin-grid{grid-template-columns:1fr}.checkin-pane{padding:14px}.checkin-nav{flex-direction:column-reverse}.checkin-nav button{width:100%}.boarding-pass-body{grid-template-columns:1fr 1fr}.boarding-pass-route strong{font-size:24px}}
    `;d.head.appendChild(style);

    q('findTripBtn').insertAdjacentHTML('afterend','<div id="manageOutput" class="booking-tool-output"></div>');
    const checkinBox=q('checkinBtn').closest('.tool-box');
    const checkinSmall=checkinBox?.querySelector('small');if(checkinSmall)checkinSmall.textContent='Simulation check-in uses a realistic airline flow, available any time after booking.';
    const checkinNote=checkinBox?.querySelector('.checkin-note');if(checkinNote)checkinNote.textContent='Choose your flight, confirm passengers and travel details, declare bags, accept the safety notice, then receive your boarding pass.';
    q('checkinBtn').insertAdjacentHTML('beforebegin','<div class="mini-form"><input id="checkinRef" placeholder="Booking reference"><input id="checkinLast" placeholder="Last name"></div>');
    q('checkinBtn').insertAdjacentHTML('afterend','<div id="checkinOutput" class="booking-tool-output"></div>');

    const gateFor=s=>{const g=run(`gateForFlight(${JSON.stringify({from:s.from,to:s.to,number:s.flightNo,time:s.time,duration:s.duration,aircraft:s.aircraft,heritage:s.heritage||false})})`);return g&&g.terminal?g:{terminal:isInternational(s)?'Terminal 4':'Terminal 5',gate:'TBD'};};
    const segmentHTML=(r,s)=>{const rec=checkinRecord(r,s),done=!!rec?.complete,g=gateFor(s);return `<div class="booking-segment"><div class="booking-segment-head"><div><b>DX ${s.flightNo} · ${s.from} → ${s.to}</b><div class="booking-meta">${fmtDate(s)} · ${fmt(s.time)} · ${s.aircraft}<br>${g.terminal} · Gate ${g.gate} · Seat ${seat(r,s,0)}</div></div><span class="checkin-state ${done?'done':''}">${done?'✓ Checked in':'Ready for check-in'}</span></div><div style="margin-top:10px"><button class="dx-action ${done?'secondary':'red'} segment-checkin" data-seg="${encodeURIComponent(key(s))}" type="button">${done?'View boarding pass':'Check in for this flight'}</button></div></div>`;};
    const showTrip=r=>{const out=q('manageOutput');out.innerHTML=`<div class="booking-card"><h3>${r.from} → ${r.to}</h3><div class="booking-meta"><b>${r.first} ${r.last}</b> · Booking <b>${r.ref}</b><br>${r.travelers} traveler${r.travelers===1?'':'s'} · Total $${r.total}</div>${(r.segments||[]).map(s=>segmentHTML(r,s)).join('')}</div>`;out.querySelectorAll('.segment-checkin').forEach(btn=>btn.onclick=()=>{const wanted=decodeURIComponent(btn.dataset.seg);q('checkinRef').value=r.ref;q('checkinLast').value=r.last;startCheckin(r,(r.segments||[]).find(s=>key(s)===wanted));q('checkinOutput')?.scrollIntoView({behavior:'smooth',block:'start'});});};
    const findTrip=()=>{const r=lookup(q('manageRef').value,q('manageLast').value);if(!r){q('manageOutput').innerHTML='<div class="booking-card"><b>Booking not found.</b><div class="booking-meta">Check the reference and last name, then try again.</div></div>';return;}showTrip(r);};

    let flow=null;
    const startCheckin=(r,segment)=>{const out=q('checkinOutput');if(!r){out.innerHTML='<div class="booking-card"><b>Booking not found.</b></div>';return;}const segments=r.segments||[];const s=segment||segments.find(x=>!checkinRecord(r,x)?.complete)||segments[0];if(!s){out.innerHTML='<div class="booking-card"><b>No flight segments found in this booking.</b></div>';return;}const existing=checkinRecord(r,s)||{};flow={r,s,step:existing.complete?4:1,selectedPax:Array.from({length:r.travelers||1},()=>true),contact:existing.contact||r.email||'',docs:existing.docs||{},bags:existing.bags||Array.from({length:r.travelers||1},()=>0),dangerousGoods:existing.dangerousGoods||false,carryOnAck:existing.carryOnAck||false};renderFlow();};
    const progress=step=>`<div class="checkin-progress">${['Passengers','Travel details','Bags & safety','Boarding pass'].map((name,i)=>`<div class="checkin-step-tab ${step===i+1?'active':''} ${step>i+1?'done':''}">${step>i+1?'✓ ':''}${name}</div>`).join('')}</div>`;

    const renderFlow=()=>{if(!flow)return;const out=q('checkinOutput'),{r,s,step}=flow;
      if(step===1){out.innerHTML=`<div class="checkin-shell">${progress(step)}<div class="checkin-pane"><h3>Select passengers</h3><div class="booking-meta">DX ${s.flightNo} · ${s.from} → ${s.to} · ${fmtDate(s)} at ${fmt(s.time)}</div>${Array.from({length:r.travelers||1},(_,p)=>`<label class="pax-check-card"><input class="pax-select" data-pax="${p}" type="checkbox" ${flow.selectedPax[p]?'checked':''}> <strong>${paxName(r,p)}</strong><small>Seat ${seat(r,s,p)} · ${s.fare||'Economy'}</small></label>`).join('')}<div class="ops-box"><b>Simulation timing override:</b> this check-in is available now even though the fictional flight date is in 2037. The remaining process follows normal airline-style steps.</div><div class="checkin-nav"><span></span><button class="dx-action red" id="ciNext" type="button">Continue</button></div></div></div>`;out.querySelectorAll('.pax-select').forEach(x=>x.onchange=()=>flow.selectedPax[Number(x.dataset.pax)]=x.checked);q('ciNext').onclick=()=>{if(!flow.selectedPax.some(Boolean))return alert('Select at least one passenger.');flow.step=2;renderFlow();};}
      else if(step===2){const intl=isInternational(s);out.innerHTML=`<div class="checkin-shell">${progress(step)}<div class="checkin-pane"><h3>Travel details</h3><div class="booking-meta">Confirm the contact and document status for the passengers checking in.</div><div class="checkin-grid" style="margin-top:12px"><label>Day-of-travel email<input id="ciContact" type="email" value="${String(flow.contact||'').replace(/"/g,'&quot;')}" placeholder="name@example.com"></label><label>Mobile number (optional)<input id="ciPhone" type="tel" value="${String(flow.docs.phone||'').replace(/"/g,'&quot;')}" placeholder="+1 555 000 0000"></label>${intl?`<label>Travel document<select id="ciDocType"><option ${flow.docs.type==='Passport'?'selected':''}>Passport</option><option ${flow.docs.type==='Permanent resident card'?'selected':''}>Permanent resident card</option></select></label><label>Issuing country<input id="ciCountry" value="${String(flow.docs.country||'').replace(/"/g,'&quot;')}" placeholder="Country"></label>`:`<label>Identification status<select id="ciDocType"><option ${flow.docs.type==='Government photo ID'?'selected':''}>Government photo ID</option><option ${flow.docs.type==='Passport'?'selected':''}>Passport</option></select></label>`}</div><label class="checkin-choice"><input id="ciNameAck" type="checkbox" ${flow.docs.nameAck?'checked':''}><span>I confirm the passenger names match the identification or travel documents that will be presented at the airport.</span></label>${intl?'<div class="ops-box"><b>International travel:</b> documents may still need verification by an airport agent before boarding. This demo does not collect or store passport numbers.</div>':''}<div class="checkin-nav"><button class="dx-action secondary" id="ciBack" type="button">Back</button><button class="dx-action red" id="ciNext" type="button">Continue</button></div></div></div>`;q('ciBack').onclick=()=>{flow.step=1;renderFlow();};q('ciNext').onclick=()=>{const email=q('ciContact').value.trim();if(!/^\S+@\S+\.\S+$/.test(email))return alert('Enter a valid contact email.');if(!q('ciNameAck').checked)return alert('Confirm that passenger names match their identification.');flow.contact=email;flow.docs={phone:q('ciPhone').value.trim(),type:q('ciDocType').value,country:q('ciCountry')?.value.trim()||'',nameAck:true};flow.step=3;renderFlow();};}
      else if(step===3){out.innerHTML=`<div class="checkin-shell">${progress(step)}<div class="checkin-pane"><h3>Bags & safety</h3><div class="booking-meta">Declare checked bags and complete the required dangerous-goods acknowledgement.</div>${Array.from({length:r.travelers||1},(_,p)=>flow.selectedPax[p]?`<div class="pax-check-card"><strong>${paxName(r,p)}</strong><small>Free checked bag included with Dextair</small><div class="checkin-grid" style="margin-top:8px"><label>Checked bags<select class="ciBag" data-pax="${p}"><option value="0" ${flow.bags[p]===0?'selected':''}>0</option><option value="1" ${flow.bags[p]===1?'selected':''}>1</option><option value="2" ${flow.bags[p]===2?'selected':''}>2</option></select></label></div></div>`:'').join('')}<label class="checkin-choice"><input id="ciDG" type="checkbox" ${flow.dangerousGoods?'checked':''}><span>I confirm no checked or carry-on bag contains prohibited dangerous goods, spare batteries packed incorrectly, explosives, flammables, or other restricted items.</span></label><label class="checkin-choice"><input id="ciCarry" type="checkbox" ${flow.carryOnAck?'checked':''}><span>I understand carry-on items must meet Dextair size rules and may need to be gate-checked if overhead space is unavailable.</span></label><div class="ops-box"><b>Airport timing:</b> arrive early enough for security and bag drop. For this simulation, boarding is shown about 35 minutes before departure and the gate closes before scheduled departure.</div><div class="checkin-nav"><button class="dx-action secondary" id="ciBack" type="button">Back</button><button class="dx-action red" id="ciComplete" type="button">Complete check-in</button></div></div></div>`;q('ciBack').onclick=()=>{flow.step=2;renderFlow();};q('ciComplete').onclick=()=>{if(!q('ciDG').checked||!q('ciCarry').checked)return alert('Complete both safety acknowledgements.');out.querySelectorAll('.ciBag').forEach(x=>flow.bags[Number(x.dataset.pax)]=Number(x.value));flow.dangerousGoods=true;flow.carryOnAck=true;r.checkin=r.checkin||{};r.checkin[key(s)]={complete:true,checkedInAt:new Date().toISOString(),contact:flow.contact,docs:flow.docs,bags:flow.bags,dangerousGoods:true,carryOnAck:true};save(r);flow.step=4;renderFlow();showTrip(r);};}
      else {const rec=checkinRecord(r,s)||{},g=gateFor(s),group=(String(s.fare||'').toLowerCase().includes('plus')||String(s.fare||'').toLowerCase().includes('eco+'))?'2':'4',board=addMinutes(s.time,-35),close=addMinutes(s.time,-15),passes=Array.from({length:r.travelers||1},(_,p)=>flow.selectedPax[p]!==false?`<div class="boarding-pass"><div class="boarding-pass-head"><b>DEXTAIR BOARDING PASS</b><span>DX ${s.flightNo}</span></div><div class="boarding-pass-route"><div><small>FROM</small><strong>${s.from}</strong></div><div class="arrow">→</div><div style="text-align:right"><small>TO</small><strong>${s.to}</strong></div></div><div class="boarding-pass-body"><div><small>Passenger</small><strong>${paxName(r,p)}</strong></div><div><small>Date</small><strong>${new Date(s.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}</strong></div><div><small>Departure</small><strong>${fmt(s.time)}</strong></div><div><small>Boarding</small><strong>${board}</strong></div><div><small>Terminal / Gate</small><strong>${g.terminal.replace('Terminal ','T')} / ${g.gate}</strong></div><div><small>Seat / Group</small><strong>${seat(r,s,p)} / ${group}</strong></div><div><small>Aircraft</small><strong>${s.aircraft}</strong></div><div><small>Checked bags</small><strong>${rec.bags?.[p]||0}</strong></div><div><small>Gate closes</small><strong>${close}</strong></div></div><div class="boarding-pass-foot"><span>Booking ${r.ref}</span><span>${isInternational(s)?'Travel document verification may be required':'Government-issued ID required where applicable'}</span></div></div>`:'').join('');out.innerHTML=`<div class="checkin-shell">${progress(4)}<div class="checkin-pane"><h3>You're checked in</h3><div class="checkin-state done">✓ Check-in complete</div><div class="ops-box"><b>Next:</b> if you have checked bags, use bag drop at the airport. Be at the gate before ${close}. Gate assignments can change, so verify airport displays on the day of travel.</div>${passes}<div class="checkin-nav"><button class="dx-action secondary" id="ciAnother" type="button">Check another flight</button><button class="dx-action" id="ciPrint" type="button">Print boarding pass</button></div></div></div>`;q('ciAnother').onclick=()=>startCheckin(r,(r.segments||[]).find(x=>!checkinRecord(r,x)?.complete)||(r.segments||[])[0]);q('ciPrint').onclick=()=>w.print();}
    };

    const checkin=()=>{const r=lookup(q('checkinRef').value,q('checkinLast').value),out=q('checkinOutput');if(!r){out.innerHTML='<div class="booking-card"><b>Booking not found.</b><div class="booking-meta">Use the booking reference generated after purchase and the passenger last name.</div></div>';return;}startCheckin(r);};
    q('findTripBtn').addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();findTrip();},true);
    q('checkinBtn').addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();checkin();},true);
    q('confirmBooking')?.addEventListener('click',()=>setTimeout(()=>{const text=q('confirmation')?.textContent||'',m=text.match(/DX[A-Z0-9]{4}/);if(!m)return;const state=run('bookingState'),segments=run('selectedSegments()'),travelers=run('travelerCount()');if(!state||!segments?.length)return;save({ref:m[0],first:q('firstName').value.trim(),last:q('lastName').value.trim(),email:q('email').value.trim(),from:state.from,to:state.to,departDate:state.departDate,returnDate:state.returnDate,total:state.total,travelers:travelers||1,seats:state.seats||{},segments,checkin:{}});},50),true);
  }

  if(frame){frame.addEventListener('load',()=>install(frame.contentDocument,frame.contentWindow));if(frame.contentDocument?.readyState==='complete')install(frame.contentDocument,frame.contentWindow);}else if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',()=>install(document,window));}else install(document,window);
})();