(() => {
  const STORE='dextairBookingsV1', SIM_NOW=new Date('2037-05-31T12:00:00');
  const frame=document.getElementById('app');
  const db=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')||{};}catch{return {};}};
  const save=r=>{const x=db();x[r.ref.toUpperCase()]=r;localStorage.setItem(STORE,JSON.stringify(x));};
  const lookup=(ref,last)=>{const r=db()[String(ref||'').trim().toUpperCase()];return r&&String(r.last).toLowerCase()===String(last||'').trim().toLowerCase()?r:null;};
  const key=s=>`${s.date}-DX${s.flightNo}-${s.from}-${s.to}`;
  const seat=(r,s,p=0)=>r.seats?.[key(s)]?.[p]||r.seats?.[key(s)]?.[String(p)]||'—';
  const eligible=s=>{const dep=new Date(s.date+'T00:00:00');dep.setMinutes(Number(s.time)||0);if(SIM_NOW<new Date(dep-86400000))return{ok:false,msg:'Check-in opens 24 hours before departure.'};if(SIM_NOW>new Date(dep-2700000))return{ok:false,msg:'Online check-in is closed for this flight.'};return{ok:true,msg:'Check-in is open.'};};
  function install(d,w){
    const q=id=>d.getElementById(id), run=code=>{try{return w.eval(code);}catch{return undefined;}}, fmt=t=>run(`hhmm(${Number(t)||0})`)||String(t);
    if(!q('findTripBtn')||q('dextairBookingFeature'))return;
    const marker=d.createElement('span');marker.id='dextairBookingFeature';marker.hidden=true;d.body.appendChild(marker);
    const st=d.createElement('style');st.textContent='.booking-tool-output{margin-top:14px}.booking-card{border:1px solid #e1e4e8;border-radius:16px;padding:16px;background:#fff;box-shadow:0 6px 18px #1111}.booking-meta{color:#6f7681;font-size:13px;line-height:1.55}.booking-segment{background:#f5f6f8;border-radius:12px;padding:12px;margin-top:8px}.checkin-state{margin-top:8px;border-radius:10px;padding:10px;background:#fff7f7;color:#7d0e14;font-size:13px;font-weight:700}.checkin-state.ok{background:#eef8f1;color:#276749}.boarding-pass{margin-top:12px;border:1px solid #d6dbe1;border-radius:16px;overflow:hidden;background:#fff}.boarding-pass-head{display:flex;justify-content:space-between;background:#111318;color:#fff;padding:12px 15px}.boarding-pass-body{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;padding:15px}.boarding-pass-body small{display:block;color:#747b86}.boarding-pass-foot{border-top:1px dashed #ccd1d8;padding:10px 15px;font-size:12px;color:#6f7681}@media(max-width:600px){.boarding-pass-body{grid-template-columns:1fr 1fr}}';d.head.appendChild(st);
    q('findTripBtn').insertAdjacentHTML('afterend','<div id="manageOutput" class="booking-tool-output"></div>');
    q('checkinBtn').insertAdjacentHTML('beforebegin','<div class="mini-form"><input id="checkinRef" placeholder="Booking reference"><input id="checkinLast" placeholder="Last name"></div>');
    q('checkinBtn').insertAdjacentHTML('afterend','<div id="checkinOutput" class="booking-tool-output"></div>');
    const segmentHTML=(r,s)=>{const e=eligible(s),done=!!r.checkedIn?.[key(s)];return `<div class="booking-segment"><b>DX ${s.flightNo} · ${s.from} → ${s.to}</b><div class="booking-meta">${new Date(s.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})} · ${fmt(s.time)} · ${s.aircraft}<br>Seat ${seat(r,s,0)} · ${s.fare||'Economy'}</div><div class="checkin-state ${done||e.ok?'ok':''}">${done?'Checked in':e.msg}</div></div>`;};
    const showTrip=r=>{q('manageOutput').innerHTML=`<div class="booking-card"><h3>${r.from} → ${r.to}</h3><div class="booking-meta"><b>${r.first} ${r.last}</b> · Booking <b>${r.ref}</b><br>${r.travelers} traveler${r.travelers===1?'':'s'} · Total $${r.total}</div>${(r.segments||[]).map(segment=>segmentHTML(r,segment)).join('')}<p><button id="tripCheckinNow" type="button">Check in</button></p></div>`;q('tripCheckinNow').onclick=()=>{q('checkinRef').value=r.ref;q('checkinLast').value=r.last;checkin();};};
    const findTrip=()=>{const r=lookup(q('manageRef').value,q('manageLast').value);if(!r){q('manageOutput').innerHTML='<div class="booking-card"><b>Booking not found.</b><div class="booking-meta">Check the reference and last name, then try again.</div></div>';return;}showTrip(r);};
    const pass=(r,s,p)=>`<div class="boarding-pass"><div class="boarding-pass-head"><b>DEXTAIR BOARDING PASS</b><span>DX ${s.flightNo}</span></div><div class="boarding-pass-body"><div><small>Passenger</small><strong>${p===0?r.first+' '+r.last:'Traveler '+(p+1)+' · '+r.last}</strong></div><div><small>Route</small><strong>${s.from} → ${s.to}</strong></div><div><small>Seat</small><strong>${seat(r,s,p)}</strong></div><div><small>Date</small><strong>${new Date(s.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}</strong></div><div><small>Departure</small><strong>${fmt(s.time)}</strong></div><div><small>Aircraft</small><strong>${s.aircraft}</strong></div></div><div class="boarding-pass-foot">Booking ${r.ref}</div></div>`;
    const checkin=()=>{const r=lookup(q('checkinRef').value,q('checkinLast').value),out=q('checkinOutput');if(!r){out.innerHTML='<div class="booking-card"><b>Booking not found.</b></div>';return;}const open=(r.segments||[]).filter(s=>eligible(s).ok||r.checkedIn?.[key(s)]);if(!open.length){out.innerHTML=`<div class="booking-card"><div class="checkin-state">No flight in this booking is currently inside the online check-in window.</div>${(r.segments||[]).map(segmentHTML.bind(null,r)).join('')}</div>`;return;}r.checkedIn=r.checkedIn||{};open.forEach(s=>{if(eligible(s).ok)r.checkedIn[key(s)]=true;});save(r);out.innerHTML=`<div class="booking-card"><h3>Check-in complete</h3><div class="checkin-state ok">Boarding passes are ready.</div>${open.filter(s=>r.checkedIn[key(s)]).map(s=>Array.from({length:r.travelers||1},(_,p)=>pass(r,s,p)).join('')).join('')}</div>`;showTrip(r);};
    q('findTripBtn').addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();findTrip();},true);
    q('checkinBtn').addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();checkin();},true);
    q('confirmBooking')?.addEventListener('click',()=>setTimeout(()=>{const text=q('confirmation')?.textContent||'',m=text.match(/DX[A-Z0-9]{4}/);if(!m)return;const state=run('bookingState'),segments=run('selectedSegments()'),travelers=run('travelerCount()');if(!state||!segments?.length)return;save({ref:m[0],first:q('firstName').value.trim(),last:q('lastName').value.trim(),email:q('email').value.trim(),from:state.from,to:state.to,departDate:state.departDate,returnDate:state.returnDate,total:state.total,travelers:travelers||1,seats:state.seats||{},segments,checkedIn:{}});},50),true);
  }
  if(frame){frame.addEventListener('load',()=>install(frame.contentDocument,frame.contentWindow));if(frame.contentDocument?.readyState==='complete')install(frame.contentDocument,frame.contentWindow);}else{if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>install(document,window));else install(document,window);}
})();